language: "zh"

pipeline:
- name: "rasa_nlu_zyb.tokenizers.jieba_tokenizer.JiebaTokenizer"
  dictionary_path: "configs/domain_words"
- name: "rasa_nlu_zyb.extractors.jieba_pseg_extractor.JiebaPsegExtractor"
  part_of_speech: ["n", "t", "ns", "constellation", "fortune"]
- name: "rasa_nlu_zyb.featurizers.bert_vectors_featurizer.BertVectorsFeaturizer"
  ip: 'localhost'
  port: 5555
  port_out: 5556
  show_server_config: True
  timeout: 7000
  check_version: False
- name: "rasa_nlu_zyb.classifiers.embedding_bert_intent_classifier.EmbeddingBertIntentClassifier"
  batch_size: 256
  epochs: 10
- name: "RegexFeaturizer"
- name: "rasa_nlu_zyb.extractors.bilstm_crf_entity_extractor.BilstmCRFEntityExtractor"
  model_type: "bilstm"
  config_proto: {
    "device_count": 4,
    "inter_op_parallelism_threads": 0,
    "intra_op_parallelism_threads": 0,
    "allow_growth": True
    }
- name: "EntitySynonymMapper"